name: ollama_test
channels:
  - conda-forge
dependencies:
  - jupyterlab=4.3.5
  - jupyterlab-plotly-extension=1.0.0
  - jupyterlab-spellchecker=0.8.4
  - matplotlib=3.8.1
  - numpy=2.2.3
  - pandas=2.2.3
  - pip=25.0
  - plotly=6.0.0
  - python=3.11
  - pip:
    - ollama==0.4.7
